---
- hosts: webserver
  become: yes
  vars:
    site_folder: site2
  tasks:
    - name: Install NGINX
      apt:
        name: nginx 
        state: present
    - name: Start NGINX service
      service:
        name: nginx 
        state: started
    - name: Copy custom index.html to NGINX web directory
      copy:
        src: "{{ site_folder }}/index.html"
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'
